### PR TITLE
Adding the Skr2 board

### PR DESCRIPTION
**Pull request by erickaby**
Tested on board, with a TFT35 and 2209 stepper drivers.

Still need to write the github builds and other motor configuration variants.

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
Thanks for submitting this. I am not ignoring you. Currently, we are working through the conflicts that are happening and need to make another release before we consider more boards.

I have not looked into the SKR 2 very much, do you think this would be a common board used for CNC's?

**Comment by mAd-DaWg** [comment]
I have this board as well for use for cncing

**Comment by Sebbeben** [comment]
check this out: https://github.com/briches94/Marlin_SKR2_MPCNC_2209_DUAL

this works great :)

**Comment by V1EngineeringInc** [comment]
This has not been widely adopted so I will close this one out.

**Pull request closed without merging**
