### PR TITLE
Enable features needed for vertical arc and helix moves

### PR DESCRIPTION
**Pull request by anttix**
CNC workplanes support (G17, G18, G19) is used to draw arcs in XZ or YZ plane to make vertical lead-in moves.
Full circles support can be used for helical plunge moves.

### CODE REVIEW

**Comment by jeffeb3** [comment]
We've played with these before, but it didn't seem like anyone was using them. If I trusted Marlin would keep them up to date, and I didn't think they would harm new users, I'd say "sure". But these builds should be targeting the beginner user, and I'm not convinced they are a good idea.

What made you want to enable them?

**Comment by anttix** [comment]
Lead-ins generated from Fusion360 for instance create a lot of small little moves without an ability to change plane with G17 G18. Fusion post uses  plane selection for Grbl and it does work well with Marlin if Marlin has these features enabled.

I have not made use of full circles support yet, although this would be very useful for helical plunges but I've been busy with other code to try it. Didn't find existing post code to copy-paste ;)

**Comment by V1EngineeringInc** [comment]
I am 90% okay with this except it could introduce errors as I doubt this has been tested very thoroughly. This would be a seldom used feature that could potentially mess up the regular users. I guess I just don't have ultimate faith this works as intended in Marlin 100% since things like the LCD or drivers gets messed up pretty frequently and they are used on a large majority of machines. I am worried we would end up being the beta testers for these features until slicers started to use them.

Maybe this would be better explained in the docs on how to enable them and why you would want to? I think CNC coordinate system and CNC planes is basically solved with G92. Does this just make helical plunges more code efficient or do you think they perform better?

On the flip side we enabled the coordinate system for one user, and it has not had any issues yet.

**Comment by jeffeb3** [comment]
I would really like to make a page with some instructions on editing from these "skeleton" configs into something more personal. Since they should all still build (better than the baseline, lol).

I have the same hesitation. And even with 24 configs, there's no way we are going to test all of these ourselves.

**Comment by anttix** [comment]
> I am 90% okay with this except it could introduce errors as I doubt this has been tested very thoroughly. This would be a seldom used feature that could potentially mess up the regular users. I guess I just don't have ultimate faith this works as intended in Marlin 100% since things like the LCD or drivers gets messed up pretty frequently and they are used on a large majority of machines. I am worried we would end up being the beta testers for these features until slicers started to use them.
> 
> Maybe this would be better explained in the docs on how to enable them and why you would want to? I think CNC coordinate system and CNC planes is basically solved with G92. Does this just make helical plunges more code efficient or do you think they perform better?

It is my understanding that G17 - G19 can not be replaced by clever use of G92. These control the plane at which arcs operate on. For example `G2 I20 J20 ` draws a full circle on X/Y (horizontal) plane. However after G18 is issued the same arc will be drawn on ZX (vertical) plane.

I don't think there is a big difference in performance at least I haven't noticed one when running off of SD card. The g-code is more efficient and files can be smaller. I saw a reduction of ~20% for a job that was doing a small part with a lot of step-downs but I never had performance problems like others have reported when disabling arcs altogether so my setup is probably not a good one to see a difference.

**Comment by anttix** [comment]
> I have the same hesitation. And even with 24 configs, there's no way we are going to test all of these ourselves.

This is off-topic and probably warrants a forum discussion but I've been thinking about this for a while and the best solution I've seen so far is a tiered "quality" metric for people to make decisions on.

E.g.

gold - configurations that V1 Engineering ships and tests on their own machines.
silver - configurations that active forum contributors have tested and reported about running well on latest stable release
bronze - configurations that active forum contributors have tested and reported about running well on the previous stable release
no rating - everything else. It may have been tested once 6mo ago, nobody knows if it still works.

The only challenge I see here is how to maintain the information about tiers as it's in constant motion. PRs to a doc page with references to forum posts to justify the tier would be one way.

Let's move this to forums if the idea seems interesting to you ;)

**Comment by jeffeb3** [comment]
I'd like to talk more about that.

I think the applicable thing to this conversation is, if we had a doc page about that, and we added someplace for advanced configuration options, would this belong there, or in every build.

I am really trying to get this to a stable state, and I've been recommending this to users on the Forums, without hearing a ton of success stories (it might be perfect, or it might be terrible, no news). I would prefer to at least postpone this change for a while, and hope v504 is a "stable" release, and IDK, maybe the next one too. Then we can at least direct people to a "known" working build while we experiment with new glorious features.

**Comment by anttix** [comment]
I'm ok, postponing this for now. Let's add an "under consideration" label and we let it rot for a few weeks and revisit ;)
Looking at the code behind these, I'm not too worried that these changes would radically alter Marlin's behavior but arcs have been full of bugs in the past so I'm fine if we don't want to take this risk for the next stable.

**Comment by anttix** [comment]
Superseded by #33  due to repository move.

**Pull request closed without merging**
