### PR TITLE
Update cnc-config

### PR DESCRIPTION
**Pull request by robertbun**
My code changes (untested) add two additional menu items to the V1 Custom menu.  One to move to XY 0,0 and one to move to Z  0.  I set the feedrate a bit below the typical maximum rapid feedrate.  Typically I see these menus being used while the bit is around the stock, and a bit slower speed gives a bit more time to react if things go sideways.

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
What happens if you use these options and have a machine without dual endstops and/or has not been homed?

**Comment by jeffeb3** [comment]
These are just G0 commands. They will just go to the origin, which will either be the place you set or homed or where the machine started. 

Related forum post:
https://forum.v1engineering.com/t/setting-home-with-lcd/24176/9?u=jeffeb3

**Comment by jeffeb3** [comment]
Here's a good point though

https://forum.v1engineering.com/t/z-zeros-at-200mm/24203?u=jeffeb3

If this was a dual lr, someone might home (up) and then go to zero, but end up crashing.

**Comment by V1EngineeringInc** [comment]
Dang it. So we can add a go to XY zero but Z would be a bad idea. For the most part, I think the only time you would ever want to do that would be probing anyway right?

So maybe remove the Z part and we can merge this in.

THANKS!

**Comment by jeffeb3** [comment]
This is a little confusing, but there is a different G38.2 command set in the dual lr firmware. If that could just overwrite this goto zero, it would be fine. It would need to bw more clear, because it is tricky right now.

**Comment by jeffeb3** [comment]
Here is the config I am talking about: https://github.com/V1EngineeringInc/MarlinBuilder/blob/main/src/configs/accessories/dual-drivers-on-yz#L17

So we could keep the Z, but make it item 4. Then make sure to add some comments to make it clear we are doing something tricky. Then just verify in the output dual lr zip that it is set right.

**Comment by robertbun** [comment]
This is the first time I’ve used GitHub for anything otherthan Zip file download.  So based onforum questions, I see some “problems” with the V1 Custom menu.  Note that I see these issues through the lensof forum questions and therefore the issues might not reflect the larger bodyof MPCNC/LowRider users:
--
Problem1: Not understanding what “Reset All Coordinates”does.
Possible solution: Rename the menu item to something like “SetXYZ to 0,0,0”
--
Problem 2: Not understanding what Home X&Y and Home Z do

Possible solution: Change the names a bit to “Home X&Yto Endstops” and “Home Z to Touchplate”
Issue: I don’t know the minimum size display you aretargeting.
--
Problem 3: Low Rider users struggle with the upwards homingas well as how to implement touch plate homing.
Possible solution: Rename the current behavior to somethinglike “Square Z axis,” and then add a 4th menu item for “Home Z [to Touchplate].”
--
Problem 4:  Homing Zdoes not take into account of the touch plate thickness nor lift the bit offthe touch plate when the homing is done.
Possible solution: I don’t see a clean solution.  It could be changed to match the code Ryanhas next to his touch plate in the store. The result would only work with Ryan’s touch plate, and it also mightbreak how people are using this menu item now. The best solution would be to introduce a g-code to set the touch plateheight that is used in the homing code. This fixes both the custom menu and the native Marlin menu while also allowing users to set the height without flashing new firmware.
--
== Rob ==

**Comment by V1EngineeringInc** [comment]
The current version of Marlin uses a new menu system, this will no longer work as is. I think I am going to close this PR.

I think we should continue this discussion after the next firmware release to see what if anything should be added to the custom menu.

I appreciate the work you put in on this one and I and sure adding a "return to 0,0" should at least be added. I forget to end my gcode with it all the time, but I would like to get some more eyes on these first.

**Pull request closed without merging**
