### PR TITLE
Change LR to be dual XZ.

### PR DESCRIPTION
**Pull request by jeffeb3**
Set up the probe the way Matthew Andres, and others have defined.

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
Why XZ instead of YZ? That rotates the work area 90 degrees, right?

**Comment by jeffeb3** [comment]
Yeah XZ is the long axis left/right (X) and the tube axis away from you (Y). I think that is how you have it set up, right? The testers in the forums all changed it to dual X.

**Comment by jeffeb3** [comment]
OK. I reverted this change. I don't want to confuse the people who are following instructions.

**Comment by V1EngineeringInc** [comment]
So this sets Z homing to max, and enables Z probing from Y max pin as well. 

Okay.

 Z max homing is a tricky one, screw that up and the LR literally falls apart. There is not an easier way to do it though. Going to need to add some instructions on this at some point.

**Comment by V1EngineeringInc** [comment]
PS we are going to need to turn down the current on the Mini at some point. 900 is pretty toasty in the summer.

**Pull request merged**
