### PR TITLE
Invert motion direction for SKR 1.3 and TMC2209 combination

### PR DESCRIPTION
**Pull request by anttix**

### CODE REVIEW

**Comment by anttix** [comment]
Continuing conversation from #5.

SKR boards use JST connectors which can not be easily reversed. Given you have correct cables of-course, but dupont does not give a secure connection when pressed into JST.

Granted, one could swap Y1 and Y2 and Z1 and Z2 to reverse the direction of Y and Z (in case of a lowrider), however X is not easily reversed and unlike dupont, where pins are easy to pull out and rearrange, it's a lot more work to dig pins out of a JST connector.
 
I noticed direction pins are inverted in Klipper's [Example SKR 1.3 config](https://github.com/KevinOConnor/klipper/blob/master/config/generic-bigtreetech-skr-v1.3.cfg). I tested it and steppers do move in the correct direction with TMC2209s. I did not try dropping in DRV8825s to see if this weird behavior where TMC2209s move in a different direction to DRV8825s is some Marlin bug and klipper folks have actually got it right or is it actually some board weirdness.

**Comment by V1EngineeringInc** [comment]
The two boards (pro and 1.3) use the exact same connectors, how is this harder to flip the plug?

Since it only effects one board I have no major issue with this one but I just have less things to try to decipher in case you two are not around.

**Comment by anttix** [comment]
> The two boards (pro and 1.3) use the exact same connectors, how is this harder to flip the plug?

I have both SKR 1.3 and SKR Pro and they both have the same JST connectors that are not easy to flip.

I think the confusion is coming from JST vs DuPont so let me clarify:



The connector on the left is DuPont, the one on the right is a JST connector the boards are designed to be used with. The latter is not reversible as it has small locking pins on one side.

One can press a dupont connector into JST but the connection is not stable because JST pins are significantly shorter than Dupont pins. There is a way to get a stable connection: One can use needle-nose pliers to carefully pull the plastic socket off of the pins. This will expose more metal for Dupont to grab onto. However I've opted to use correct connectors and I'd recommend that to other people as well.

Note that the JST connector used on SKRs is different from the locking connectors used on Rambo boards. The ones on Rambo have pins that are as long as dupont so it's safe to use regular Dupont plugs in lieu of the locking ones.

**Comment by V1EngineeringInc** [comment]
I have never seen steppers actually come with those connectors, I know the boards do. My steppers and my wires come with Dupont. Since I don't sell that board I don't mind making any changes you want to it. 

If people use the machine in a non standard orientation the firmware will need to be changed again. (The first year I flip flopped on this several times with my firmware, then decided the user can do this edit if needed).

Would it not be easier jut to make this specific to this board and not bother with adding an option?

**Comment by anttix** [comment]
> I have never seen steppers actually come with those connectors, I know the boards do. My steppers and my wires come with Dupont. Since I don't sell that board I don't mind making any changes you want to it.

SKR Pro boards are also fitted with JST connectors. This is an annoyance and people generally have to source different cables e.g. these https://www.amazon.com/dp/B07VQBX16V as these connectors seem to be popular on 32bit boards. Pretty much every 32bit board I've been able to get my hands on uses these. SKR, Makerbase (Robin and friends), 9-axis board from Flymaker etc.

One other way (besides pulling the plastic socket off the board) I've seen people work around this is to add a dab of hot glue to keep the dupont in JST socket.

> Would it not be easier jut to make this specific to this board and not bother with adding an option?

It's not *easier* per-se, but it is an issue that seems to be specific to this particular board. I may have been over-estimating the usefulness of axis flipping for other situations. I'll post an update that is specific to SKR + 2209 combination.,

**Comment by jeffeb3** [comment]
You can also pull out the first two pins on the jst and swap those.

I just don't like setting any of the invert flags because I feel responsible for all the invert flags. I'd rather just consider this to be an issue for the wiring.

**Comment by anttix** [comment]
> You can also pull out the first two pins on the jst and swap those.
> 
> I just don't like setting any of the invert flags because I feel responsible for all the invert flags. I'd rather just consider this to be an issue for the wiring.

Except that it is not ;) Exactly the same wires work with DRV8825s on exactly the same board. They work with both DRV8825s and TMC2209s on SKR Pro. Clearly there is something going on in the software configuration that makes TMC2209s to rotate in a different direction on SKR 1.3.

**Comment by jeffeb3** [comment]
Except that it is :) and we've treated it that way for a long time. We have it written in the docs that way, and I can't remember the last time someone had a problem with it.

This system is designed by the experts, but it is targeting the novice. There is very little utility making a system that automatically configures firmware for the anttix's of the world. Anttix knows how to configure firmware already. Not many people have the 1.3, drvs, and 2209s. Of those people, how many aren't comfortable swapping some cables around? Of those, how many are unwilling or invapable of changing the invert flags themselves? Maybe just one :)

**Comment by anttix** [comment]
> Except that it is :) and we've treated it that way for a long time. We have it written in the docs that way, and I can't remember the last time someone had a problem with it.

The times of saying: "Just reverse the connector" are coming to an end. The vast majority of 32bit boards in the wild today come with JST-XH connectors that are not reversible. Getting the direction right in software is getting more and more important as a result. It would be nice if Marlin had a way to reverse axis from the menu or with Gcode the same way one can tweak stepper current without rebuilding the firmware but it has not and even if it did, standard wiring should work out of the box. E.g. if someone buys a stepper and cables and plugs into an SKR 1.3 with TMC2209s it should turn in the right direction.

**Comment by V1EngineeringInc** [comment]
So this can wait until we see a stepper or my custom wires that come with JST? 

I have never seen one actually come with anything other than DuPont. Duet's come with something even more different the common thread is they all work with DuPont, which are easily reversible So while I continue to make DuPont based wires we don;t have to worry about direct flags, right?

**Comment by anttix** [comment]
> Duet's come with something even more different the common thread is they all work with DuPont, which are easily reversible

Duet3 comes with beefier connectors that are physically larger and have a different pitch so dupont can't be pushed onto these any more. Duet2 had smaller connectors. The fact that the connector fits is mostly incidental though and does not mean it is been designed to work. 2.54mm pitch is common in electronics and dupont connector is very slim so there is a chance it can be pushed into pretty much any socket that has pins spaced 2.54mm apart. If you look closely, JST-XH pins are a tad larger than dupont pins, but the difference is small enough so they can be forced in. However JST-XH is not compatible with dupont because the pins are too short to form a reliable connection. I've seen these come out from my boards multiple times, especially on lowrider where the board is subjected to more vibrations. This is why I bothered to re-crimp the connectors in the first place.

It's a simple test: Press dupont into JST-XH and shake the wire left and right. It's pretty easy to work it loose like this. Now try to do the same when dupont is attached to a Ramps board. It will be a lot more difficult to work it loose there.

**Comment by V1EngineeringInc** [comment]
So this can wait until we see a stepper or my custom wires that come with JST? If all common steppers currently ship with dupont I see no need for this setting. Less settings changed less things to go wrong.

**Comment by anttix** [comment]
I don't quite get why this change should wait for anything. It doesn't matter what connectors stepper motors generally come with: Dupont connectors are not compatible with JST-XH, one is advised to get the correct cables. If a novice decides to self-source steppers with correct cables and an SKR 1.3 board, they will run into this issue. What is the recommendation going to be then? Dig the pins out of connectors? Buy dupont cables and risk these coming loose?

**Comment by jeffeb3** [comment]
If you need to wire it yourself, then we don't have to fix this in the firmware. If you use dupont connectors, then you can just flip them (and sure, there's risk, but I am sure we aren't going to change that from here). If you buy cables, and they connect to motors, at least some of those will be dupont connectors, which can easily be swapped. You can also "dig out" two pins and swap them. It's not that hard, and you can also download the zip, change the direction flag, and compile it yourself. You could also just cut two wires and solder them together the other way. Ryan also sells wiring kits, I'm not sure which connectors or direction those are wired up.

I don't agree that we need to fix this in the firmware. I don't agree that this is an issue that we need to track here.

But, I can also see you feel strongly about it, and I am not interested in arguing forever about it. If you really want to invert these flags, then I'm ok with it. 

I really don't want to get in a fight about it (maybe a little late) and I am very thankful that you care and everything you've done already. In the effort of peace, and friendship, I think we should just accept this, unless it causes problems for the purchased kits and wiring harnesses Ryan sells.

**Comment by anttix** [comment]
Thank you @jeffeb3 . How's that for a path forward. I'll report this bug to Marlin and see what they say. If they close this as not something they want to deal with, we will not deal with this either. I guess the best recommendation then would be to tell newbies is to stay away from SKR 1.3 boards :) If Marlin does ack this as a bug, let's carry this change until there is a fix upstream.

**Pull request closed without merging**
