### PR TITLE
Add filament change option to the 3D printer configs.

### PR DESCRIPTION
**Pull request by V1EngineeringInc**
Teaching Tech's filament sensor video inspired me to try it out and, dang, filament swaps are a piece of cake now. Almost no chance of messing it up!

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
Shoot, I am not really sure why it is failing. See anything obvious?

**Comment by jeffeb3** [comment]
They were failing overnight. I think the arduino downloads are failing.

**Comment by jeffeb3** [comment]
No, wait. That is the wrong permissions on the new files (they aren't set to be executable).

**Comment by V1EngineeringInc** [comment]
Is that something I missed?

**Comment by jeffeb3** [comment]
The file isn't executable. It won't let me fix it though.
```
drwxrwxr-x 2 jeffe jeffe 4096 Oct  8 22:00 .
drwxrwxr-x 5 jeffe jeffe 4096 Oct  8 22:00 ..
-rwxrwxr-x 1 jeffe jeffe  146 Aug  7 19:39 aero-extruder
-rw-rw-r-- 1 jeffe jeffe  594 Oct  8 22:00 auto-filament-change
-rwxrwxr-x 1 jeffe jeffe  559 Aug  7 19:39 drv8825
-rwxrwxr-x 1 jeffe jeffe  440 Aug  7 19:39 dual-drivers-on-xy
-rwxrwxr-x 1 jeffe jeffe  873 Oct  8 21:14 dual-drivers-on-xz
-rwxrwxr-x 1 jeffe jeffe  840 Oct  8 21:14 dual-drivers-on-yz
-rwxrwxr-x 1 jeffe jeffe  139 Aug  7 19:39 dummy-extruder
-rwxrwxr-x 1 jeffe jeffe   79 Aug  7 19:39 mk8-extruder
-rwxrwxr-x 1 jeffe jeffe  432 Aug  7 19:39 no-dual-endstops
-rwxrwxr-x 1 jeffe jeffe  286 Oct  8 21:14 reprap_discount_full_graphic_lcd
-rw-rw-r-- 1 jeffe jeffe  214 Oct  8 22:00 reprap_discount_smart_controller
-rwxrwxr-x 1 jeffe jeffe  957 Oct  8 21:14 tmc2130
-rwxrwxr-x 1 jeffe jeffe  936 Oct  8 21:14 tmc2209
-rwxrwxr-x 1 jeffe jeffe  591 Oct  8 21:14 use-32-microsteps
```
This is a linux thing, AFAIK, but git keeps track of the permissions on the files. The repap_discount_smart_controller and the auto-filament-change don't have the `x` set on them, so they can't be executed. I have no idea how to change that in windows. It is trivial to do in linux, and I've changed it, but it says I don't have permission to push to this repo:
```
remote: Permission to V1EngineeringInc/MarlinBuilder.git denied to jeffeb3.
fatal: unable to access 'https://github.com/V1EngineeringInc/MarlinBuilder/': The requested URL returned error: 403
```

**Comment by jeffeb3** [comment]
Looks like the magic command for you is: `git update-index --chmod=+x 'name-of-shell-script'`

It also looks like I do not have write permissions anymore. I think this all started about when I asked them to break the fork relationship with jeffeb3/MarlinBuilder. Can you just try to give me write permission again?

**Comment by V1EngineeringInc** [comment]
Yeah you were completely gone from the repo. Fixed?

So is this something that is write protected because it hasn't been merged?

**Comment by jeffeb3** [comment]
These scripts are for Linux, and when github runs them, they are ran in Linux. One of the "features" of Linux is that any file is just a file. It doesn't become a program, that you can execute, until you set the x bit on that file. There are three x permissions on every file. One for the owning user, one for the owning group, and one for everyone. Extenstions mean almost nothing to Linux.

If you want to make a script that you can run, like a program, you need to put the commands to want to run inside, and then you need to set the x bit(s). Then Linux knows it is not just a file you can read and write, it is also a file it can execute.

There are a bunch of important security rules that come from doing this everywhere, but the important thing is that if you get a file that needs to be ran, you need to set the x bit.

Git can keep track of which files in Linux need to have the x bit set. So if I check out this repo, all the other scripts are going to have the x bit set properly. When the github action checks out this repo, it also has the x bits set properly. But when it checked out this new file, the x bit wasn't set, so the linux machine that runs our github actions couldn't execute that script, so it stopped and gave us a :x:.

I don't know the right way to solve this from your perspective. You want to make new files in windows (or the web UI), and then commit them to git. But windows doesn't have a concept of an x bit. So after you make the file and add it in, it won't have the x bit set. You can force git to treat that file like it has the x bit with that `git update-index` command I pasted. But that is going to be tricky to remember.

The only logical solution is for you to delete windows all together and come join the dark side. If you can get ubuntu to run a web browser, then you'll be able to ask me for help with the rest. :smile: 

On the second issue, where I was no longer a collaborator. That seems totally fixed.

**Comment by V1EngineeringInc** [comment]
After some googling I see that it seems to be a common sourcetree issue, Hope to find a fix. Not ready for full command line yet.

The odd part is I copied your file, renamed it and then edited it. You would think it would keep the exact permissions. On the windows side digging in the permissions they appear identical.

**Pull request merged**
