### PR TITLE
Let's see if this works.

### PR DESCRIPTION
**Pull request by jeffeb3**
2.0-bugfix checks to see if we set the extruder steps/mm, and if we have EXTRUDERS=0, then it fails a sanity check.

This is a little complicated, because the dual endstop accessory applies to any board, but the steps/mm is dependent on the board and drivers. So I set it once in the dual accessory script, and then I reset it again in the configs with 200,200,800 and dual endstop.

I have a feeling this will fix bugfix, and break 2.0.8.

### CODE REVIEW

**Comment by jeffeb3** [comment]
This looks like it is still broken. I wonder if our rambo test case is still active in the main Marlin firmware.

**Comment by jeffeb3** [comment]
The rambo dual XY, with EXTRUDERS=0 is still active in MarlinFirmware, but the skr pro uses TMC2209s, and the TMC library has some print_e methods, which aren't defined. I think this needs to get fixed upstream.

**Comment by jeffeb3** [comment]
Something is also wrong with the skr turbo builds. They are 8825. It looks like something wrong with the endstop names. I'm not sure, but maybe we had a hack that is no longer needed.

**Comment by V1EngineeringInc** [comment]
How and the heck..I had no idea. I was getting emails about the skrturbo, but nothing about the other boards. 

I will try to get up to speed on what you are looking at.

**Comment by jeffeb3** [comment]
I ignored them for a few days, hoping it would return to normal. But I decided to try it out this morning.

I added a test case to MarlinFirmware for CNC dual endstop, no extruder a while ago. I think that has helped keep us more stable (because all the PRs have to pass on that build scenario). I think I should probably add one for skr pro. 

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/tests/rambo#L45

**Comment by V1EngineeringInc** [comment]
I can't figure out why I only get notifications for the turbo. That must have been the newest workflow added and the others came in from your original test build. If you see a way to add me to the notifications please do. All the boxes and drop-downs I can find I have set to notify on all events and mentions. 

I remember that test case, it surely helps!

**Comment by jeffeb3** [comment]
I don't know either. I assume it is based on the particular actions, but I don't know how to pull up those settings directly.

**Comment by jeffeb3** [comment]
There are some settings here, but I don't see anything specific to a specific action. Is your email client sorting them somehow?

https://github.com/settings/notifications

**Comment by V1EngineeringInc** [comment]
Oh I think that link was promising. There was the first box unchecked "Automatically watch repositories "

**Comment by V1EngineeringInc** [comment]
https://stackoverflow.com/questions/62304258/github-actions-notifications-on-workflow-failure

Looks like I am not just missing something. Maybe if I make an edit and commit it, it will add me? At the top of the actions it shows you for all but the turbo, which shows me. Do you get turbo notifications?

**Pull request closed without merging**
