### PR TITLE
Added more configurations. These seem logical, but how can you tell?

### PR DESCRIPTION
**Pull request by jeffeb3**
#60 

This fills in the matrix a little. I don't have plans to test these. We really need a way to mark which ones are "Official" vs. "Maybe garbage".

Sorry, I accidentally pushed this straight to main, but I fixed it.

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
On the releases page how are they sorted? In order of your matrix?

Can we swap it around buy popularity maybe. rambo skr mini ramps Archim.

 Then maybe add all non official boards with a different prefix, instead of V1CNC maybe do just CNC or something?

**Comment by jeffeb3** [comment]
I assume it is either alphabetical. The only other order that would make any sense is the order that the builds finished, but they are more organized than that.

**Comment by V1EngineeringInc** [comment]
This is good to go right or does the PR for the DOCS builder page conflict with this?

**Comment by jeffeb3** [comment]
Good to go. The docs stuff should work before and after this.

**Pull request merged**
