### PR TITLE
archim1 microstepping issues fixed

### PR DESCRIPTION
**Pull request by V1EngineeringInc**

### CODE REVIEW

**Comment by jeffeb3** [comment]
Weird, but ok.

**Comment by V1EngineeringInc** [comment]
So is there anything I should do after the next "release" Are we leaving this going. It only works in Pio but it does work.

**Comment by jeffeb3** [comment]
If it works with pio, then I'm fine with leaving it in without arduino. I was thinking we would leave it off so you wouldn't have had to go through this level of work again for this board. If we hit another big snag, I will again think about just dropping it instead of trying to limp along. 

Maybe we could add something to the readme? But I don't think anyone is reading those. Or maybe the docs?

**Comment by V1EngineeringInc** [comment]
Okay, I am going to test it real quick. I know I had both options enabled at some point, so I wonder if a bunch of the issues we have had were when that got taken out.

I think it is time for a 509? Back to junction deviation so faster smoother operation the reason for a 509 and laser enabled on a couple boards.

What are you thinking in the readme? For the Archim, if so I think we can wait for it to go bad again and just call the most recent release the last one.

This means I can go back to playing with the 6 pack controller.

**Comment by jeffeb3** [comment]
Whenever you want. The laser stuff seems like a good enough reason to release. This will still be based on 2.0.7.2. 

All the tools are still there to build with arduino, but it will fail. So I am hoping people will know to use pio instead.

**Comment by V1EngineeringInc** [comment]
I can leave that in the release notes and firmware page for sure, archim requires Pio

**Pull request merged**
