### PR TITLE
Add a configuration for SkrTurbo with TMC2208

### PR DESCRIPTION
**Pull request by undingen**
This is based on the TMC2209 support and I just changed all occurrences to TMC2208.
I only tested the no end stop version but this seemed to work fine.

I'm not familiar with this chips so not sure if I also need to change features or currents.

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
Aren't the stealthchop settings and current different?

**Comment by undingen** [comment]
How do I know if they have to be different? I can't see any special casing in Marlins `Configuration_adv.h` or so.
Do I have to find the right values by monitoring the debug output of  `M112`? I have until now only connected a the TFT35 but can test next time connect a laptop and see what it outputs.

**Comment by V1EngineeringInc** [comment]
See what your current is set at in your LCD or let it run and see how hot your steppers get.

I'm not sure this is going to get merged or not, the 2209 are the same price have more features and can handle more current. Let me think about it if the settings are correct.

**Comment by undingen** [comment]
I bought the TMC2208 accidentally and switched now to the 2209 because of the newer features and build in support (and maybe I can also try grblHAL with it later on).
But it seems the 2208 did also work (did not get hot or so I could also switch to stealth chopping in the menu etc so UART seems to work too). But the the 2209 seem to be quieter per default than the 2208 with my config.

So I'm fine with closing this PR and not merging it - if somebody ever ends up accidentally buying the 2208 like me they can try this config.

**Pull request closed without merging**
