### PR TITLE
Sensorless homing base configuration

### PR DESCRIPTION
**Pull request by anttix**
This can be merged while we sit on #6 to gather more data on how this fares with different machines.

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
Bear with me hear. For sensorless homing you have to set an appropriate trigger current and for our machines it could be any axis or combo of axis. So no matter what some user firmware edits are required. I think this one is best as an instruction page in the docs as well.

Here is the downsides of sensorless homing, here is how you set up all the options need to to make it work, Here is how to wire your board, here is how to test it.

If we enable it here this could instantly more than triple the number of builds. The one that seems plausible to me is maybe setting up a standard LowRider sensorless config as I think the loss in resolution will be fine there....but that 100% needs to be tested first and options would need to be in place to buy that default set of hardware.

Just because we can automate 1k builds does not mean we need to. I just want to proved solid starting points for a few choice boards. Think about what it takes for a new user to even flash firmware. I really do not want them to come here and have to scroll through 3 pages of cryptic build names as a step one in doing that.

**Comment by anttix** [comment]
Agreed, we do not want to vend ton of firmware options.  Shared code that allows one to turn on sensorless homing does not increase the number of available machine configurations, that's why I split if off from PR #6 

It just makes it easier for advanced users to experiment with it if they so choose by making a small one-line change to machine config instead of more invasive changes.

For "general public", there are a two options IMO:

- By machine type e.g. all lowrider configurations with compatible drivers use sensorless homing
- By diver type e.g. all TMC2209 configurations use sensorless homing

It's probably too early for the second option as we don't know what the precision loss really is. For 3D printers, sensorless homing on the Z axis is considered too imprecise for good bed adhesion however Prusa does use it for squaring the Z, their firmware drives gantry all the way up against hard stops to square it. Granted they also have a bed probe. When well tuned, it may be plenty accurate for squaring CNC axes but there are a lot of variables accuracy also depends on such as the "softness" of the contact point. I think the safe bet is to move first with LRs as there is no good physical switch option there and if this is a success, maybe consider sensorless homing for MPCNCs on boards fitted with compatible drivers.

**Comment by V1EngineeringInc** [comment]
Okay, I guess the non sensor less stuff confused me.

So you are saying this, at least for now, Is just an option that someone submits a PR for and gets a build to pop out in the actions tab? Then the PR gets deleted? 

Sorry you know I have zero clue how git actually works. That is the only way I know how to make a non standard build happen.

**Comment by jeffeb3** [comment]
I'd really like to have a better front page to find these builds and sort them by usefulness. I think having some experimental builds in that case would help me. I just wrote a book to someone who is wanting the plug and play experience with these bleeding edge features.

So I am thinking again about a nice webpage, with some radio buttons and some clear text on what not to do. And the selection of the radio buttons will point to a specific zip file.

@vicious1, putting in a script for SH just means anttix can run thw build from his computer, or a fork of the repo, or from a branch and use that feature, but a new release won't have any builds with that enabled. But getting it in will help him combine that change with other new stuff he's trying.

**Comment by jeffeb3** [comment]
This still has some other features rolled into it. Z2 Stall sensitivity? And the small fixes branch.

**Comment by anttix** [comment]
> This still has some other features rolled into it. Z2 Stall sensitivity? And the small fixes branch.

Z2_STALL_SENSITIVITY is required for sensorless homing to operate correctly. It defaults to Z_STALL_SENSITIVITY but only if it's not commented out, which it is in Marlin default Configuration_adv.h

**Comment by jeffeb3** [comment]
You have those options set in the 2209 settings though. Can we move those into the sensorless homing script? Then we won't be affecting the 2209 builds we have.

**Comment by anttix** [comment]
> You have those options set in the 2209 settings though. Can we move those into the sensorless homing script? Then we won't be affecting the 2209 builds we have.

We can potentially move Z2_STALL_SENSITIVITY to ```accessories/sensorless-homing``` but for the rest of the settings this is not the right place because these values are driver specific. For example TMC2130s use values from -63 to 63 while TMC2209s have a range from 255 to 0. Thus in order to have somewhat sane defaults, one has to make these driver specific.

The entire block is guarded by ```#if EITHER(SENSORLESS_HOMING, SENSORLESS_PROBING)```. Given neither is set by default, it should have no effect whatsoever on builds that do not enable sensorless homing.

**Comment by V1EngineeringInc** [comment]
For simplicity, for me, I would really prefer anything that can be isolated to be isolated. Referring to Z2. When I work backwards to find an issue the less files I have to open the better.

This still seems not righto me. For a sensorless base we don't know what machine it would be used for and Z2 is only for a LR, what about the MPCNC? So do we need a sensorless base, and a LR and MPCNC options to also go with it?

**Comment by anttix** [comment]
One can view ```Z2_STALL_SENSITIVITY``` to be very similar to all of the ```Z2_DRIVER_TYPE``` setting. 
We set it for all machines even if it's only applicable to Lowrider. Likewise we set ```X2_DRIVER_TYPE``` in Lowrider configs although it is not applicable there. These settings are inert until the actual axis is enabled elsewhere.

Granted it is not as clean looking in Marlin config, however the scripts are currently not designed to handle such variations well. E.g. we have a single TMC2209 and DRV8825 config which is not customizable per machine type.

**Comment by V1EngineeringInc** [comment]
Does Z also need to be enabled?

https://github.com/MarlinFirmware/Marlin/blob/4268d86da18ce8ffffc8236e0895fd2f3ba7f95d/Marlin/Configuration_adv.h#L2516

**Comment by anttix** [comment]
> Does Z also need to be enabled?
> 
> https://github.com/MarlinFirmware/Marlin/blob/4268d86da18ce8ffffc8236e0895fd2f3ba7f95d/Marlin/Configuration_adv.h#L2516

Yes. With current config it is implicitly turned on by opt_set, however when enabling these options is moved to another file, it should be explicit.

**Comment by anttix** [comment]
The last update I pushed now explicitly turns on Z stall sensitivity if sensorless homing is enabled.

**Comment by anttix** [comment]
Superseded by #31 due to repository move.

**Pull request closed without merging**
