### PR TITLE
Updated Readme; Fixed build; Added Wifi option for SKR Pro LR;

### PR DESCRIPTION
**Pull request by vic10us**
Fixed the build broken due to obsolete/migrated parameters HOMING_FEEDRATE_XY and HOMING_FEEDRATE_Z.
I also added a new configuration for those who are using the Wi-Fi module on SERIAL_PORT 6.
And finally, to help those who would like to build this without the Github actions, I updated the readme to aid. This should work for any Linux or WSL2 setup but it was only tested on WSL2 and Ubuntu 20.04.

### CODE REVIEW

**Comment by jeffeb3** [comment]
That name is confusing. :)

Thank you for the PR. Sorry it took me so long to take a look.

1. The readme. I like that it has these instructions, but a) I'm not sure they are right. You are installing pip, but not platformio? I would also suggest using virtualenv, which would make the platformio installation stay separate from whatever else you're doing with python on your system. b) Since this repo is for people who come here just to find and install the firmware once (and aren't experts) we need to be really careful not to lead people into the path of trying to install WSL or something just to use these scripts. I think it would be good to have instructions though, so maybe put these in a readme in another folder, or a different .md file?
2. Wifi on serial port 6. This looks like a good change. The consequence is not clear, but you will lose the ability to use the TFT this way. I'd like to keep this for the future, but I'd really like to focus on stability before adding any new configs.
3. The changes for upstream marlin parameter changes. I'd like to merge this RN, but I can't because all these things are in the same PR. We should break this up so we can get this change in right away. I sure would like it if our scripts told us when we were trying to change something that didn't exist...

**Comment by V1EngineeringInc** [comment]
Sorry I read through this when you first posted it. I guess I didn't make any notes.

I'm with Jeff for #3 if you can separate it out. #2, same, most of our users will have the TFT so I would assume this would be a bit of a small user base to maintain a config for.

**Comment by vic10us** [comment]
Thanks for the review. I guess I am a bit confused when it comes to the purpose of this repo. 

Reply to no. 1: I really don't see anyone without a minimum of technical knowledge using these scripts. 98% of the user base who will want to use them will most likely be Windows users who will have serious difficulty running these scripts without the use of WSL. As for moving the instructions to another file, I don't mind, but it is really not how most repositories are managed so I defaulted to the standard README.md. If this were a larger repo I would suggest using the wiki functionality but in this case, it would be extreme overkill... IMHO.

Reply to no. 2: As for the Wi-Fi, the new config does not disable the TFT display, it disables the USB serial, which I felt was a decent compromise seeing as the point of adding Wi-Fi was to replace direct serial communication.

Reply to no. 3: Marlin makes a lot of breaking changes when they are not supposed to. Especially when it comes to config key renaming. I wish they followed SemVer standards more. I see the logic in separating the change as that was the main reason for this PR. I will separate it and do another PR.

**Comment by jeffeb3** [comment]
3) Agreed. I have meant to make some new sed scripts that will by smarter and will know when a config changes. At least then we will have the error right away.
2) I agree with you in concept, but USB is still really important. You added this as a separate config, and that is totally fine. That's the way this is supposed to work. I want to wait to make this change though, because I still want to have more confidence that people can find the right version, and that this firmware is solid before adding more configs. But I do want to support this. I would like to be able to support this in a way that caused the least amount of confusion for users.
1) 99% of the people who use this repo should just be directed straight to the releases. Most users should not be using these scripts. I don't want to confuse 5% of those 99% to give instructions to the 1% that want to run these scripts.

I hope to get a chance to fix the #define today in some form. I want my inbox back. :+1:

**Comment by vic10us** [comment]
I am closing this PR and I will open separate ones for each change.

**Pull request closed without merging**
