### PR TITLE
Bump to 2.0.7.2

### PR DESCRIPTION
**Pull request by V1EngineeringInc**
See if I do it right.

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
Is that all it takes?

**Comment by jeffeb3** [comment]
Not quite. There is another line in each file that  is still on 2.0.7.1. The very next line.

**Comment by V1EngineeringInc** [comment]
Sorry I bet I just flooded your inbox as well.

I could not figure out how to do my changes externally I kept getting errors so I did them in GitHub....Still learning.

**Comment by V1EngineeringInc** [comment]
Okay, I think it is good. I will merge, test real quick and hit another release. This should be a stable one for a while.

**Pull request merged**
