### PR TITLE
Testing out removing the extra HAL directories.

### PR DESCRIPTION
**Pull request by jeffeb3**
This is me trying to delete HAL folders that get ignored in platformio, but are left in the arduino builds, which breaks the builds in windows.

I'm not sure I have the HAL folders right, especially for the skr pro.

### CODE REVIEW

**Comment by jeffeb3** [comment]
Oh, this could be great. @V1EngineeringInc, can you download one of these zips and see if it builds in arduino in windows? The rambo ones specifically, but the ramps should also work.

**Comment by V1EngineeringInc** [comment]
How can I test this?

**Comment by V1EngineeringInc** [comment]
I see it now, checks tab

**Comment by V1EngineeringInc** [comment]
So The rambo dual bugfix works for me....but it always has.

Tested the fresh 2.0.6.1, wow doesn't work

Arduino ide 1.8.12

Dam you are my hero! Fixed a problem before I knew it was a problem.

**Pull request merged**
