### PR TITLE
SD init fail issue fix

### PR DESCRIPTION
**Pull request by V1EngineeringInc**
Not sure I did that right, do I need to specify the value that is already there?

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
I don't understand why some of those are failing and others are not. Either way I think that is a bugfix bug, hopefully fixed by the next actions cycle.

**Comment by V1EngineeringInc** [comment]
When the bugfix works again, This and a few small tweaks (lcd scrolls backwards, endstops are opposite) on the zen firmware should be good for a V510?

**Comment by jeffeb3** [comment]
You need to put it on a separate line and use opt_set.

**Comment by jeffeb3** [comment]
It looks like bugfix is just broken for some of the boards. The rambo builds worked for 2.0.7.2

**Comment by V1EngineeringInc** [comment]
Okay I wasn't sure because in the 2.0.7.2 it is a full line and each option is separate, in the bug fix it is a variable option, but it is already set. On top of that it is in config advanced in one and just config in the other.

The fails are odd, they changed "speed" to "feed rate" but it looks like they missed some of them. Not sure why only some boards trigger it.

**Comment by jeffeb3** [comment]
This morning, it looks like bugfix is just broken. I have no idea if this fix worked on a 2.0.7.2 build. But we should probably just wait for bugfix to fix itself upstream. The nightlies broke too.

**Comment by V1EngineeringInc** [comment]
Okay, I will check out the 2.0.7.2 asap.

**Comment by V1EngineeringInc** [comment]
Kinda odd. I just ran the plain current bugfix, it failed. I did nothing and reran it and it worked. I swear it had to do with a new version of u8glib getting installed in p.io Could that effect the builder?

**Comment by jeffeb3** [comment]
Yeah. It gets the latest packages for every build.

**Comment by V1EngineeringInc** [comment]
DAng.

The skrpro the only one failing is the 3dp. This is too odd, I guess give it another day or two.

**Comment by V1EngineeringInc** [comment]
Getting closer but this PR didn't take. Bug fix branch

```
#if ENABLED(SDSUPPORT)
  /**
   * SD Card SPI Speed
   * May be required to resolve "volume init" errors.
   *
   * Enable and set to SPI_HALF_SPEED, SPI_QUARTER_SPEED, or SPI_EIGHTH_SPEED
   *  otherwise full speed will be applied.
   *
   * :['SPI_HALF_SPEED', 'SPI_QUARTER_SPEED', 'SPI_EIGHTH_SPEED']
   */
  //#define SD_SPI_SPEED SPI_HALF_SPEED
```

**Comment by jeffeb3** [comment]
It looks like qe set XY_HOME_SPEED in the 3dp config. They renamed it to XY_HOME_FEEDRATE. We can do one of these:

1. Disable that setting right now.
2. Make sure 2.0.7.2 builds are all working and ignore the fact that bugfix is broken. It won't stop the release builds, because they are all based on 2.0.7.2.
3. Write a gate to decide what to call the setting based on the version number. I can do this from my keyboard today or tomorrow. I am pretty sure I did this before. We will probably need to do this in the future.
4. Wait for the next Marlin release (2.0.8?)

I prefer 2. Second choice is 3.

**Comment by jeffeb3** [comment]
> Getting closer but this PR didn't take.

What do you mean? It didn't properly set the setting?

I really don't want to release against bugfix. Is there a way to fix this in 2.0.7.2 and just get 510 out? We can rework it when they release 2.0.8, which seems like it will be soon.

**Comment by V1EngineeringInc** [comment]
The setting did not change in either version.

I am fine with just sticking with 2.0.7.2, I just get nervous when the BF doesn't work.

**Comment by V1EngineeringInc** [comment]
Previous code was the BF, this is 2.0.7.2

```
/**
 * SD CARD: SPI SPEED
 *
 * Enable one of the following items for a slower SPI transfer speed.
 * This may be required to resolve "volume init" errors.
 */
//#define SPI_SPEED SPI_HALF_SPEED
//#define SPI_SPEED SPI_QUARTER_SPEED
//#define SPI_SPEED SPI_EIGHTH_SPEED

```

**Comment by jeffeb3** [comment]
That should still work. I can take a look and see what is up. 

I am glad we know what is coming with bugfix, and I would like to have the nightlies working. I can look for a simple fix.

**Comment by V1EngineeringInc** [comment]
Typo!?

opt_set, instead of opt_ser?

**Comment by jeffeb3** [comment]
Yeah. A typo. I also added the if (and tested locally, but who knows) to check the version. After we get a new stable version, we can undo that if statement. But if we leave it in, it should still default to the new names.

Hopefully these are green, and if so, you can give it a test with the long cables on a 2.0.7.2 branch.

**Comment by jeffeb3** [comment]
> This and a few small tweaks (lcd scrolls backwards, endstops are opposite) on the zen firmware should be good for a V510?

Is this actually the list of issues to fix? Or are there more?

**Comment by V1EngineeringInc** [comment]
Sweet!

That is all I think. I have that list on my desk. I have not changed them yet.

**Comment by jeffeb3** [comment]
Something is funny with the reversing encoder. I was going to push a fix, but it looks like that has been reversed in the past.

The REVERSE_ENCODER_DIRECTION is set in two places:
- src/configs/boards/rambo
- src/configs/accessories/reprap_discount_smart_controller (not full discount)
It looks like this was intentional, and you changed it in september with this comment: 
> 
    Update reprap_discount_full_graphic_lcd
    
    The full graphic lcd is reversed on all boards but the full rambo. This is the fix.
    Also adding a screen timeout to return home after 3 minutes.

So it looks like the rambo is always reversed, but the skr, and mini rambo are not. I am guessing we really want rambo and mini-rambo, but not the skr, is that right?

It looks like no-dual-endstops sets xmin and ymin to inverting: true. I think that is wrong, and I think that file is correctly being used in the zxy builds. So I think we just need to fix that.

**Comment by jeffeb3** [comment]
This can be merged. Moving the zxy stuff to here: https://github.com/V1EngineeringInc/MarlinBuilder/pull/70

**Comment by V1EngineeringInc** [comment]
Shoot okay. The SKR is definitely opposite the rambo and mini, not sure where the ramps stands. I will have to double check.

**Comment by V1EngineeringInc** [comment]
I will test it after mail pickup.

**Comment by V1EngineeringInc** [comment]
Didn't work in the bugfix and enabled and changed all three lines in 2.0.7.2.

/**
 * SD CARD: SPI SPEED
 *
 * Enable one of the following items for a slower SPI transfer speed.
 * This may be required to resolve "volume init" errors.
 */
#define SPI_SPEED SPI_HALF_SPEED
#define SPI_SPEED SPI_HALF_SPEED
#define SPI_SPEED SPI_HALF_SPEED

Wait this is all in the zen fix now? I'll check there and this gets closed?

**Comment by jeffeb3** [comment]
I expected it to change all three lines. We can't fix that (and it is harmless) unless we make our own opt set scripts.

I am fine with merging this. Any idea why it wasn't working in bugfix? We are going to have that issue come back in a week or few.

The zenxy is based on this branch, so the tests would pass. We should merge this PR first.

**Comment by V1EngineeringInc** [comment]
Gotcha.

I think I might have opened the wrong bugfix. I deleted them and doubled checked on the zen fix and they are all good.

**Pull request merged**
