### PR TITLE
Experimental Lowrider2 sensorless homing configuration

### PR DESCRIPTION
**Pull request by anttix**

### CODE REVIEW

**Comment by jeffeb3** [comment]
I don't have any problems with this, except it pulls in the changes from the other PR.

**Comment by V1EngineeringInc** [comment]
This one definitely needs to get some sort of accuracy testing to be sure. I love the idea, and sensor less could be a very easy option on the LR.

I have not made any end stop choices on the SKR's as I want to test the sensor less stuff first.

I am not sure if all the other stuff mixed in has come in on the other PR but if this is clean now let's sit on it until some testing is done.

**Comment by anttix** [comment]
> This one definitely needs to get some sort of accuracy testing to be sure. I love the idea, and sensor less could be a very easy option on the LR.

I reported on homing repeatability (not necessarily accuracy) [here](https://forum.v1engineering.com/t/lowrider-skr-1-3-dual-y-and-z-tmc2209-uart-sensorless-homing/14596/11)

For Z I got < 0.01 mm for X/Y < 0.02 mm. 

However this was when homing down, with well tuned stallguard settings and making sure X hits the side of the plate not the side of roller mounts on the plate. If the homing location is flexible, like if X is homed further up where plate can flex some, repeatability did suffer quite a bit.

If we get some experimental builds going we can ask people to test to see if I'm just lucky or the method is indeed accurate enough.

**Comment by anttix** [comment]
I have created PR #11 that just includes base configuration and none of the actual machines. This way it should be easier to experiment while not publishing images (yet).

**Comment by jeffeb3** [comment]
Do you want to close this one then?

**Comment by anttix** [comment]
> Do you want to close this one then?

It's an open question how experimental firmwares should be distributed for forum folks to test. If we keep this open, I can point ppl to the builds in this PR. The main difference from posting links to a forked repository is that builds are kept up to date with v1/main automatically and comments will be posted to the main repository instead of being lost somewhere in a fork.

I know Marlin has a ton of PRs open with labels like "Needs: Discussion" "Needs: Testing" "help wanted" etc. and they close these based on how long ago there was any activity.

I think it's a good model but ultimately it's up to project maintainers to decide if partial work is better tracked in an open PR or somewhere else.

**Comment by jeffeb3** [comment]
This is fine for now. I'm just wanting to get all the current PRs addressed somehow. But I'm also rushing it a little because we all have focus right now.

**Comment by V1EngineeringInc** [comment]
> The main difference from posting links to a forked repository is that builds are kept up to date with v1/main automatically

So if we do not merge this it still stays up to date? That opens up all sorts of possibilities.

**Comment by jeffeb3** [comment]
It does, and it doesn't. It will build against new changes in Marlin, but changes to main need to be pulledback into this branch.

**Comment by anttix** [comment]
Superseded by #32 due to repository move.

**Pull request closed without merging**
