### PR TITLE
follow current Marlin

### PR DESCRIPTION
**Pull request by V1EngineeringInc**

### CODE REVIEW

**Comment by jeffeb3** [comment]
There are two places where we check for 2.0.7.2:

https://github.com/V1EngineeringInc/MarlinBuilder/blob/main/src/configs/common/3dp-config#L14

https://github.com/V1EngineeringInc/MarlinBuilder/blob/main/src/configs/accesories/reprap_discount_full_graphic_lcd#L9

I think that is because in <=2.0.7.2, there was a different name. I think we can delete these and keeo the else.

**Comment by V1EngineeringInc** [comment]
Whoa, I did not even remember that. Thanks

I guess I will take a look but I think you are right, not needed with this release.

**Comment by jeffeb3** [comment]
I don't remember these things either. I just searched (grep) for 2.0.7.2 and saw them.

**Comment by V1EngineeringInc** [comment]
Shoot, we need to merge this right?

**Comment by jeffeb3** [comment]
We don't have to merge it until we want to release. But it isn't doing anything useful sitting here.

There is a newer version out though, which is one thing I thought we were waiting for. 2.0.8.2. We should probably just go to that.

**Comment by V1EngineeringInc** [comment]
So this might trigger me to actually receive notifications...if not you are stuck with them.

**Comment by V1EngineeringInc** [comment]
Right, The 8.2, let me adjust these, maybe it will fix some of the failing builds as well as get me notifications.

**Comment by jeffeb3** [comment]
We will see after this gets merged if the issues with bugfix snuck into 2.0.8/2.

You can also merge this, and just make another one for 2.0.8.2. It's flexible like that.

**Comment by V1EngineeringInc** [comment]
Hmmmm, these are all going to fail I think. Merge it anyway? Or should I stop screwing around and focus on making the current version work?

**Comment by jeffeb3** [comment]
I don't care if bugfix is failing (it is failing in main, so this isn't a regression). But I would like to see that 2.0.8.2 succeeds. If it fails, then I would either merge 2.0.8, or just wait. I don't think there is a pressing reason to be on the bleeding edge if it is broken.

We do need to take the other issue upstream, I think.

**Comment by jeffeb3** [comment]
Well, crud. Those issues have gotten from bugfix into 2.0.8.2.

**Comment by V1EngineeringInc** [comment]
And...the custom LCD menu is all borked as well. I am working on that first since I know I can fix that easy enough.

**Comment by jeffeb3** [comment]
I want to work with you on this, but I have to work today. I think it would be useful to get the skr dual test upstream, and let the devs soak on it for a few days, at least. Hopefully, then they will figure out what got broken.

I suspect we won't have a release for 2.0.8.2 though, since these problems aren't going to be fixed upstream.

**Comment by V1EngineeringInc** [comment]
No worries at all!

I just got the Rambo shipment so I will be busy as well. Just farting around while ingesting large amounts of coffee.

**Pull request merged**
