### PR TITLE
Disable the archim arduino build.

### PR DESCRIPTION
**Pull request by jeffeb3**
This disables the archim arduino builds. I am just about ready to disable the archims all together. I am not sure if publishing the platformio builds is a good idea, because my memory is that the platformio build or flash didn't work as well as the arduino one did.

### CODE REVIEW

**Comment by jeffeb3** [comment]
Did I break the actions? Why aren't they testing this PR?

**Comment by V1EngineeringInc** [comment]
Looks like maybe the limit was hit for the day or it has at least been throttled. I forgot to test the Pio version to see if it works or not. I am pretty sure 508 can be the last if Pio doesn't work.

**Comment by jeffeb3** [comment]
If the pio doesn't work, then we should remove the archim all together from the releases. I think that isn't too hard to do. We can even leave it building. But if we don't have anything that works in 509, then we shouldn't include the archim zips.

**Comment by V1EngineeringInc** [comment]
Since these are failing, it doesn't even output the marlin raw folder to test.

Is there something I am missing? I was hoping to get the output of our configs, compile it myself with Pio and see if it works.

**Comment by V1EngineeringInc** [comment]
Trying to get a 509 out soon to fix the junction deviation thing.

**Comment by jeffeb3** [comment]
OK. That passed, so that should kill the nastygram in our inboxes every morning :+1: 

w.r.t. the pio build/test. Here is one thing we can do:
1. Release a 509.
2. Let it run and publish the archim builds
3. Download those builds
4. Edit the release to remove those builds
5. Test them by flashing with pio
6. Upload them back into the release (the ones we downloaded from step 3) if the test passes

In between 4 and 5, no one will be getting the 509 build and making the assumption it should work.

**Comment by V1EngineeringInc** [comment]
Gotcha

**Comment by V1EngineeringInc** [comment]
Well, the laser frequency setting has had some work, as well as arcs. Looks like I might need to do a little extra testing on 509.

**Comment by V1EngineeringInc** [comment]
Hmmm 1/2/21 build is not working on Pio or Arduino.

**Comment by jeffeb3** [comment]
I don't know what you mean. It looks like the archim builds are running and passing. Is there something I'm missing?

**Comment by V1EngineeringInc** [comment]
Still working on it. It compiles and flashes with pio but doesn't work, Arduino is giving me the file length error.

**Comment by V1EngineeringInc** [comment]
Well, as usual something is funky.

This has to be done every time for P.io to work. https://forum.v1engineering.com/t/archim-1-issues-after-software-update/22413/6?u=vicious1

`M351 S1 X1 Y1 Z1 E1 B1
M351 S2 X1 Y1 Z1 E1 B1
M351 S3 X1 Y1 Z1 E1 B1
M500`

The odd thing is M500/502 are not working on today's bugfix (for the one flash I tried).

I will try it again tomorrow, it makes too much noise. I don;t want to wake everyone up.

**Comment by jeffeb3** [comment]
I think we should report that back into Marlin. I bet they just missed resetting the microsteps in the eeprom code. It should be quick for them to fix.

**Comment by jeffeb3** [comment]
Once you fix the usteps, does it work?

**Comment by V1EngineeringInc** [comment]
Sorry for the delay.
Yes, it works after setting them. I used today's version. Still the same thing M500 and M502 in repetier are not doing anything. I swear they used to work. I wonder if it is related.

**Comment by V1EngineeringInc** [comment]
https://github.com/MarlinFirmware/Marlin/issues/20664

**Comment by V1EngineeringInc** [comment]
Well I think that did it. Odd but awesome!

I will try the files after they finish the test.

**Pull request merged**
